services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - default

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    networks:
      - default

networks:
  default: